### ISSUE TITLE
output embedding shape

### ISSUE THREAD

**Issue by daydayupPro** [zekarias-tilahun/GAP#2]
From the log, I get the number of nodes is 2211, and I run the demo `python gap.py`.
From the output file, `gap_global_15.emb` only has embeddings of 970 nodes.
And how can I get all nodes' embeddings

**Comment by zekarias-tilahun** [comment]
What you saw from the log, 2211 is from the initial reading of the graph. However, since you have specified the training rate to be 0.15, GAP will sample a fraction of (15%) the edges for training. This leads to using the nodes incident to the sampled edges (970). If you want to learn an embedding for all the nodes you have to specify the training rate as 1.0

**Comment by daydayupPro** [comment]
Nice shot, I have rerun the model and saw the output results, thank you!
